restcountries/urls.py
"""Defines URL patterns for 'restcountries'"""

from django.urls import path

from . import views

app_name = 'restcountries'
urlpatterns = [
    path('', views.index, name='index'),
    path('country/<int:pk>', views.country, name='country'),
    path('edit_country/<int:pk>', views.edit_country, name='edit_country'),
    path('search_country', views.search_country, name='search_country'),

    # Paths for exposing the REST API

    # JSON response containing all countries in a list
    path('rest/all/', views.api_all, name='api_all'),
    # JSON response of a single country
    path('rest/country/<str:name>/', views.api_country_name, name='api_country_name'),
    # JSON query of neighbors of a specific country
    path('rest/neighbours/<str:name>/', views.api_neighbours, name='api_neighbours'),
    # JSON query of countries speaking the language provided
    path('rest/language/<str:language>/', views.api_same_language,
         name='same_language'),
    # JSON query by search pattern
    path('rest/search_country/<str:search_term>/', views.api_search_country,
         name='api_search_country'),
]

strativ_assignment/urls.py
from django.contrib import admin
from django.urls import path, include

from .api import router
from restcountries.api_views import LanguageList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('restcountries.urls')),
    path('api/', include(router.urls)),
    path('api/language/<str:language>', LanguageList.as_view()),
    path('api-auth/', include('rest_framework.urls'))
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

restcountries/models.py
from django.db import models

# Create your models here.
class Country(models.Model):
    """Country model having all attributes as specified"""
    name = models.CharField(max_length=200)
    alphacode2 = models.CharField(max_length=3)
    capital = models.CharField(max_length=200)
    population = models.BigIntegerField()
    timezone = models.CharField(max_length=20)
    flag = models.CharField(max_length=200)
    languages = models.CharField(max_length=500) # TODO: make it a choicefield
    neighbouring_countries = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'countries'

    def __str__(self):
        return f'{self.name[:50]}'

users/models.py
from django.db import models

# Create your models here.

restcountries/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.forms.models import model_to_dict
from django.forms import ModelForm
from django.contrib.auth.decorators import login_required

from .models import Country

class CountryForm(ModelForm):
    class Meta:
        model = Country
        fields = '__all__'

@login_required
def index(request):
    countries = Country.objects.all()
    return render(request, 'restcountries/index.html', {'countries':countries})

@login_required
def country(request, pk):
    country = Country.objects.get(pk=pk)
    return render(request, 'restcountries/country.html', {'country':country})

@login_required
def edit_country(request, pk):
    if request.method != 'POST':
        country = Country.objects.get(pk=pk)
        form = CountryForm(instance=country)
    else:
        form = CountryForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('restcountries:index')

    context = {'form': form}
    return render(request, 'restcountries/edit_country.html', context)

@login_required
def search_country(request):
    query = request.GET.get('name')
    if query:
        countries = Country.objects.filter(name__icontains=query)
        return render(request, 'restcountries/search.html', {
            'countries': countries
        })
    else:
        return HttpResponseRedirect(reverse('index'))

def api_all(request):
    countries = Country.objects.all()
    countries_list = list(countries.values())

    return JsonResponse(countries_list, safe=False)

def api_country_name(request, name):
    try:
        country = Country.objects.get(name__iexact=name)
        return JsonResponse(model_to_dict(country))
    except Exception as er:
        print(er)
        err = {'message': 'Sorry. That country name does not exist'}
        return JsonResponse(err, status=404)

def api_search_country(request, search_term):
    """
    JSON response returning all countries where names contain 'search_term'
    """
    countries = Country.objects.filter(name__icontains=search_term)
    if countries.count() > 0:
        countries_list = list(countries.values())
        return JsonResponse(countries_list, safe=False)
    else:
        err = {'message': 'Your search term matched no country names'}
        return JsonResponse(err, status=404)

def api_neighbours(request, name):
    """
    Return as strings alpha3Code encoded list of neighbours of the specified
    country.
    """
    try:
        country = Country.objects.get(name__iexact=name)
        neighbours = country.neighbouring_countries
        return JsonResponse({'neighbours': neighbours})
    except Exception as er:
        print(er)
        err = {'message': 'Sorry. That country name does not exist'}
        return JsonResponse(err, status=404)

def api_same_language(request, language):
    """
    JSON Response list of all countries speaking 'language'
    """
    # Some sanity checks
    if len(language) < 1:
        err = {'message': 'Language cannot be of zero length.'}
        return JsonResponse(err, status=400)
    else:
        # Check if language name has digits in it
        # Could be easier using regex
        chars = list(language)
        hasDigits = True

        for digit in range(10):
            if digit in chars:
                break
        else:
            hasDigits = False

        if hasDigits:
            err = {
                'message': 'Your language name has digits. Sorry, robot \
                languages not supported yet.'
            }
            return JsonResponse(err, 404)

    same_lang_countries = Country.objects.filter(languages__icontains=language)
    countries_list = list(same_lang_countries.values())

    return JsonResponse(countries_list, safe=False)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            newuser = form.save()
            login(request, newuser)
            return redirect('restcountries:index')
    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

restcountries/templates/restcountries/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <!-- Bootstrap 4.4.1 from CDN -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'restcountries/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Strativ Assignment</h2>
                <form action="{% url 'restcountries:search_country' %}" method="GET">
                    <input class="search" type="text" name="name" placeholder="Search by name">
                </form>

                {% if user.is_authenticated %}
                  Hello, {{ user.username }}<br>
                  <a href="{% url 'users:logout' %}">Log out</a><br>
                {% else %}
                <a href="{% url 'users:register' %}">Register</a><br>
                <a href="{% url 'users:login' %}">Log in</a><br>
                {% endif %}

                <div>
                    <a href="{% url 'restcountries:index' %}">Home</a>
                </div>
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

restcountries/templates/restcountries/country.html
{% extends "restcountries/base.html" %}

{% block title %}
    Countries List | Strativ Assignment
{% endblock %}

{% block body %}
    <h1>Country: {{ country.name }}</h1>

                <p>Name: {{ country.name }}</p>
                <p>Alplhacode2: {{ country.alphacode2 }}</p>
                <p>Capital: {{ country.capital }}</p>
                <p>Timezone: {{ country.timezone }}</p>
                <p>Population: {{ country.population }}</p>
                <p>Flag: <a href="{{ country.flag }}">{{ country.flag }}</a></p>

                <p><strong>Neighbours:</strong> {{ country.neighbouring_countries }}</p>
                <p><strong>Languages spoken:</strong> {{ country.languages }}</p>
{% endblock %}

restcountries/templates/restcountries/edit.html
{% extends "restcountries/base.html" %}

{% block title %}
    Countries List | Strativ Assignment
{% endblock %}

{% block body %}
    <h1>Country: {{country.name}}</h1>

    {{ form.as_p }}
    <!--
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>No.</th>
                <th>Name</th>
                <th>Alplhacode2</th>
                <th>Capital</th>
                <th>Timezone</th>
                <th>Population</th>
                <th>Flag</th>
                <th>Details</th>
            </tr>
        </thead>
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ country.name }}</td>
            <td>{{ country.alphacode2 }}</td>
            <td>{{ country.capital }}</td>
            <td>{{ country.timezone }}</td>
            <td>{{ country.population }}</td>
            <td><a href="{{ country.flag }}">{{ country.flag }}</a></td>
            <td>askdj</td>
        </tr>
    </table>
    -->
{% endblock %}

restcountries/templates/restcountries/edit_country.html
{% extends "restcountries/base.html" %}

{% block title %}
    Edit Country | Strativ Assignment
{% endblock %}

{% block body %}
    <h1>Edit Country: {{ form.name.value }}</h1>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
        
    </form>
{% endblock %}

restcountries/templates/restcountries/index.html
{% extends "restcountries/base.html" %}

{% block title %}
    Countries List | Strativ Assignment
{% endblock %}

{% block body %}
    <h1>All Countries</h1>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Alphacode2</th>
                <th>Capital</th>
                <th>Timezone</th>
                <th>Population</th>
                <th>Flag</th>
                <th>Details</th>
            </tr>
        </thead>
        {% for country in countries %}
        <tr>
            <td>{{ country.name }}</td>
            <td>{{ country.alphacode2 }}</td>
            <td>{{ country.capital }}</td>
            <td>{{ country.timezone }}</td>
            <td>{{ country.population }}</td>
            <td>{{ country.flag }}</td>
            <td><a href="{% url 'restcountries:country' country.pk %}">Details</a></td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

restcountries/templates/restcountries/search.html
{% extends "restcountries/base.html" %}

{% block title %}
    Countries List | Strativ Assignment
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Alphacode2</th>
                <th>Capital</th>
                <th>Timezone</th>
                <th>Population</th>
                <th>Flag</th>
                <th>Details</th>
            </tr>
        </thead>
        {% for country in countries %}
        <tr>
            <td>{{ country.name }}</td>
            <td>{{ country.alphacode2 }}</td>
            <td>{{ country.capital }}</td>
            <td>{{ country.timezone }}</td>
            <td>{{ country.population }}</td>
            <td>{{ country.flag }}</td>
            <td><a href="{% url 'restcountries:country' country.pk %}">Details</a></td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}